frontend/models/DashboardForm.php
<?php
namespace frontend\models;

use Yii;
use yii\base\Model;
use common\models\User;
use yii\helpers\VarDumper;

class DashboardForm extends Model{
    public $name;
    public $userid;
    public $gender;
    public $role;
    public $photo;
    public $settings;
    public $test1_name;
    public $test1_best_result;
    public $test1_best_result_date;
    public $test2_name;
    public $test2_best_result;
    public $test2_best_result_date;
    public $test3_name;
    public $test3_best_result;
    public $test3_best_result_date;
    public $test4_name;
    public $test4_best_result;
    public $test4_best_result_date;



    public function __construct( $userid ){

        //Yii::$app->user->identity
        $this->userid = $userid;
        $this->refreshAttributes( );
    }

    private function refreshAttributes(){

        $_user = User::findIdentity( $this->userid );
        $this->name = $_user->name;
        $this->gender = $_user->gender;
        $this->photo = $_user->photo;
        $this->role = $_user->role->title;
       // $this->settings = $_user->settings;
        $this->test1_name = Test::findOne(1)->title;
        $this->test2_name = Test::findOne(2)->title;
        $this->test3_name = Test::findOne(3)->title;
        $this->test4_name = Test::findOne(4)->title;
        $res_array = Result::find()->where(['userid' => $_user->userid, 'testid' => 1 ])->orderBy('result')->one();
        $this->test1_best_result = $res_array['result'];
        $this->test1_best_result_date = $res_array['date_participate'];

    }

    public function attributeLabels()
    {
//        return [
//            'email' => Yii::t('app', 'E-mail address'),
//        ];
    }
}

// VarDumper::dump($_user);
//die;

frontend/models/Test.php
<?php

namespace frontend\models;

use Yii;
use common\components\CustomVarDamp;

/**
 * This is the model class for table "test".
 *
 * @property integer $idTest
 * @property string $title
 * @property string $type
 */
class Test extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'test';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['type'], 'string'],
            [['title'], 'string', 'max' => 20],
            [['title'], 'unique']
        ];
    }

    public function getBestResult()
    {
        $result = 0;
        $res_query = $this->hasOne(Result::className(), ['testid' => 'testid'])->andFilterWhere(['userid' => Yii::$app->user->id])->orderBy(['result' => SORT_ASC])->one();
        if ( $res_query !== null )
            $result = $res_query->result;


        return $result;

    }

    public function getLastResult()
    {
        $result = 0;
        $res_query = $this->hasOne(Result::className(), ['testid' => 'testid'])->andFilterWhere(['userid' => Yii::$app->user->id])->orderBy(['date_participate' => SORT_DESC])->one();
        if ( $res_query !== null )
            $result = $res_query->result;


        return $result;

    }
    //@todo rewrite accordingly to DRY principle
    public function getBestResultDate()
    {
        $result = Yii::t('app', 'not defined');
        $res_query = $this->hasOne(Result::className(), ['testid' => 'testid'])->andFilterWhere(['userid' => Yii::$app->user->id])->orderBy(['result' => SORT_ASC])->one();
        if ( $res_query !== null )
            $result = Yii::$app->formatter->asDate( $res_query->date_participate , 'medium' );


        return $result;

    }
    //@todo rewrite accordingly to DRY principle
    public function getLastResultDate()
    {
        $result = Yii::t('app', 'not defined');
        $res_query = $this->hasOne(Result::className(), ['testid' => 'testid'])->andFilterWhere(['userid' => Yii::$app->user->id])->orderBy(['date_participate' => SORT_DESC])->one();
        if ( $res_query !== null )
            $result = Yii::$app->formatter->asDate( $res_query->date_participate , 'medium' );


        return $result;

    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idTest' => Yii::t('app', 'Id Test'),
            'title' => Yii::t('app', 'test name'),
            'type' => Yii::t('app', 'control test - launch after some days (5 by default) after usual test. Usual test user can launch every day without limitation'),
        ];
    }
}

frontend/controllers/DashboardController.php
<?php

namespace frontend\controllers;

use common\models\User;
use Yii;
use frontend\models\Result;
use frontend\models\Test;
use frontend\models\SignupForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use common\components\CustomVarDamp;

class DashboardController extends \yii\web\Controller
{
    public function behaviors()
    {
        // @ todo - rewrite - now it's to clumsy
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'test', 'index', 'profile', 'viewResults'],
                'rules' => [
                    [
                        'actions' => ['logout', 'test', 'index', 'profile', 'results'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {

        $user_model = User::findIdentity(Yii::$app->user->id);

        $dataProvider = new ActiveDataProvider([
            'query' => Test::find(),]);

        return $this->render('index',
            ['user_model' => $user_model,
                'dataProvider' => $dataProvider]);
    }

    public function actionProfile()
    {
        $model = new SignupForm(['scenario' => 'profile']);
        if ($model->load(Yii::$app->request->post()) && $model->profile()) {
            return $this->redirect(['dashboard/index']);
        } else {
            return $this->render('profile', [
                'model' => $model,
            ]);
        }

    }

    public function actionResults()
    {
        $testId = 0;
        $get_array = Yii::$app->request->get();

        if( isset( $get_array['testid'] ) )
            $testId = $get_array['testid'];

        $dataProvider = new ActiveDataProvider([
            'query' => Result::find()->andFilterWhere(['userid' => Yii::$app->user->id, 'testid' => $testId]),
            'pagination' => [
                'pageSize' => 2,
            ],]);

        return $this->renderAjax('results',
            ['dataProvider' => $dataProvider]);
    }


    public function actionTest()
    {
        return $this->render('test');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

frontend/views/dashboard/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use common\components\ListViewWithoutSummary;
use frontend\assets\DashboardAsset;


DashboardAsset::register($this);
?>
<div class="dashboard-index">

    <div class="row">
        <div class="col-lg-5">

            <?=
            Yii::$app->formatter->asImage($user_model->photo, ['width' => "70", 'height' => "70"]);
            ?>
            <?= DetailView::widget([
                'model' => $user_model,
                'attributes' => [
                    'name',
                    'role',
                ],
            ]) ?>

            <?= Html::a('Edit user profile', ['dashboard/profile']) ?>

        </div>
    </div>

    <br/>
    <br/>

    <div class="row">
        <div class="col-lg-5">

            <?= ListViewWithoutSummary::widget([
            'dataProvider' => $dataProvider,
            'itemView' => 'itemListResult',
            ]);?>
        </div>
    </div>

    <br/>
    <br/>
    <?= Html::a('LogOut', ['dashboard/logout'], ['class' => 'btn btn-primary', 'name' => 'logOut', 'data-method' => 'post']) ?>

    <?php
    Modal::begin([
        'header'=>'<h4>Результаты</h4>',
        'id' => 'modal',
        'size'=>'modal-lg',
    ]);

    echo "<div id='modalContent'></div>";

    Modal::end();
    ?>

</div><!-- dashboard-index -->

frontend/views/dashboard/itemListResult.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;



?>
<div class="post">

    <table class="table">

            <h4> <?=Html::encode($model->title) ?> </h4>

        <tbody>

        <tr class="success">
            <td>Лучший результат</td>
            <td><?=HtmlPurifier::process( $model->bestResultDate )?></td>
            <td><?=HtmlPurifier::process( $model->bestResult )?></td>
        </tr>


        <tr class="info">
            <td>Последний результат</td>
            <td><?=HtmlPurifier::process( $model->lastResultDate )?></td>
            <td><?=HtmlPurifier::process($model->lastResult)?></td>
        </tr>

        <tr>
            <td>
                <?= Html::button('Все результаты', ['value'=>Url::to(['dashboard/results', 'testid' => $model->testid]),'class' => 'btn btn-success','id'=>'modalButton']) ?>
            </td>
            <td>
                <?= Html::a("Запустить тест", ['dashboard/test', 'testid' => $model->testid ], ['class' => 'btn btn-success', 'name' => 'Test']) ?>
            </td>
            <td>

            </td>


        </tr>

        </tbody>

    </table>



</div>

frontend/views/dashboard/profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use frontend\assets\ProfileAsset;

/* @var $this yii\web\View */
/* @var $model frontend\models\SignupForm */
/* @var $form ActiveForm */

ProfileAsset::register($this);
$this->title = 'User profile';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="signup">

    <h2><?= Html::encode($this->title) ?></h2>

    <?php
    $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);
    $_user = Yii::$app->user->identity;
    $default_name = $_user->name;
    $default_gender = $_user->gender; ?>


        <?= $form->field($model, 'name', ['inputOptions' => ['value' => $default_name]]) ?>
        <?= $form->field($model, 'gender')->dropDownList(['male' => 'male', 'female' => 'female']) ?>


<div class="form-group">
    <?= $form->field($model, 'photo', ['inputOptions' => ['id'=>'input-2', 'label' => Yii::t('app', 'Выбирете файл аватара'),
        'type'=>'file', 'class'=>'file', 'multiple'=>'false', 'data-show-upload'=>'false', 'data-show-caption'=>'true', 'uploadUrl' => 'dashboard/index']])->fileInput() ?>
</div>

<!--    <input id="input-2" type="file" class="file" multiple="false" data-show-upload="true" data-show-caption="true">-->

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end();
    ?>
    <?= Html::a('Вернуться в кабинет', ['dashboard/index'], ['class' => 'btn btn-primary', 'name' => 'Return',]) ?>

</div><!-- signup -->

frontend/views/dashboard/results.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\SerialColumn;

/* @var $this yii\web\View */
/* @var $model frontend\models\DashboardForm */
/* @var $form ActiveForm */
?>

    <div class="row">
        <div class="col-lg-5">


            <?=  GridView::widget([
                'dataProvider' => $dataProvider,
                    'columns' => [['class' => SerialColumn::className()],
                        'date_participate',
                        'result',
                ]]
            ) ?>

            <?= Html::a('Вернуться в кабинет', ['dashboard/index'], ['class' => 'btn btn-primary', 'name' => 'Return',]) ?>
        </div>
    </div>

frontend/views/dashboard/test.php
<?php
/* @var $this yii\web\View */
use frontend\assets\TestPerfofmingAsset;

TestPerfofmingAsset::register($this);
?>
<h1>dashboard/test</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>